// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:lang": {
    params: {
      "lang": string;
    };
  };
  "/:lang/connect/jira": {
    params: {
      "lang": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:lang" | "/:lang/connect/jira";
  };
  "pages/index.tsx": {
    id: "pages/index";
    page: "/:lang";
  };
  "pages/connect/jira.tsx": {
    id: "pages/connect/jira";
    page: "/:lang/connect/jira";
  };
};